code cleanup
InsanusMokrassar/TelegramBotAPI-examples pull request #275
Opened 2024-07-10 16:26 UTC by bpavuk

optimized imports here and there, made CustomBot work as intended

2024-07-10 16:32 UTC, InsanusMokrassar requested changes

2024-07-10 16:32 UTC, InsanusMokrassar commented on HelloBot/src/main/kotlin/HelloBot.kt
> +                    message.ifFromChannelGroupContentMessage<Unit> {
what for this explicit type?:)

2024-07-10 16:32 UTC, InsanusMokrassar commented on RightsChangerBot/src/main/kotlin/RightsChanger.kt
> +    bot.buildBehaviourWithFSMAndStartLongPolling(
it is better to left here explicit type, even if it is not required

2024-07-10 16:32 UTC, InsanusMokrassar commented on RightsChangerBot/src/main/kotlin/RightsChanger.kt
> +                ?: return@strictlyOn null
imho, it is better here to left explicit if not null check instead of `?:`

2024-07-10 16:32 UTC, InsanusMokrassar commented on StarTransactionsBot/src/main/kotlin/StarTransactionsBot.kt
>  suspend fun main(vararg args: String) {
If you may, it would be nice to add description for this bot

2024-07-10 16:37 UTC, bpavuk commented on HelloBot/src/main/kotlin/HelloBot.kt
> +                    message.ifFromChannelGroupContentMessage<Unit> {
without that, Nothing is inferred instead. this may cause instability (and it failed to run on my machine consistently due to this)

2024-07-10 16:37 UTC, bpavuk commented on RightsChangerBot/src/main/kotlin/RightsChanger.kt
> +    bot.buildBehaviourWithFSMAndStartLongPolling(
why?

2024-07-10 16:38 UTC, bpavuk commented on RightsChangerBot/src/main/kotlin/RightsChanger.kt
> +                ?: return@strictlyOn null
`?:` is always cleaner

2024-07-11 10:54 UTC, InsanusMokrassar commented on RightsChangerBot/src/main/kotlin/RightsChanger.kt
> +    bot.buildBehaviourWithFSMAndStartLongPolling(
Because of otherwise type will be inferred and potentially it will break Idea sometimes

2024-07-11 10:54 UTC, InsanusMokrassar commented on RightsChangerBot/src/main/kotlin/RightsChanger.kt
> +                ?: return@strictlyOn null
`?:` is always shorter, but `clean` is very... undefined definition. In my opinion, code with `?:` will be less clean due to its less readability in difference with long lines

2024-07-11 13:55 UTC, merged